sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t prebenmd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prebenmd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-622811839783"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  